#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
lie_splitting_solver.py

Path 1 (Two-Language-friendly):
  - Treat the compiled C++ prior solver as a black-box step map S_dt.
  - Train a corrector Phi_theta to map prior outputs to reference outputs:
        y_ref ≈ Phi_theta( y_prior )
  - Export Phi_theta as TorchScript for C++ (libtorch) inference.

Assumptions:
  - You already have a dataset (X, Y, dt) where
        X: state at time t
        Y: reference state at time t + dt (generated by small-step RK4, dt_small=1e-3)
  - The compiled prior is the harmonic oscillator flow map:
        x' = y, y' = -x
    implemented in C++/Eigen and invoked as:
        prior_oscillator_eigen <input_bin> <output_bin>

Binary protocol (float64):
  input_bin:
    int64 N
    float64 dt
    then N rows of (x, y) float64
  output_bin:
    int64 N
    then N rows of (x_next, y_next) float64
"""
import argparse
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset


@dataclass
class TrainCfg:
    batch_size: int = 1024
    epochs: int = 200
    lr: float = 2e-3
    weight_decay: float = 0.0
    seed: int = 0
    width: int = 128
    depth: int = 3
    dtype: torch.dtype = torch.float64
    dt: float = 0.1


def set_seed(seed: int):
    np.random.seed(seed)
    torch.manual_seed(seed)


class MLP(nn.Module):
    def __init__(self, in_dim=2, out_dim=2, width=128, depth=3):
        super().__init__()
        layers = []
        d = in_dim
        for _ in range(depth):
            layers.append(nn.Linear(d, width))
            layers.append(nn.GELU())
            d = width
        layers.append(nn.Linear(d, out_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

class ResidualCorrector(nn.Module):
    """
    C_dt(u) = u + dt * g_theta(u)
    """
    def __init__(self, width=128, depth=3):
        super().__init__()
        self.g = MLP(3, 2, width=width, depth=depth)

    def forward(self, u: torch.Tensor, dt: float) -> torch.Tensor:
        dt_t = torch.tensor(dt, dtype=u.dtype, device=u.device)
        batch_size = u.shape[0]
        if dt_t.dim() == 0: 
             dt_feature = dt_t.view(1, 1).expand(batch_size, 1)
        else: 
             dt_feature = dt_t.view(-1, 1)
             if dt_feature.shape[0] == 1:
                 dt_feature = dt_feature.expand(batch_size, 1)
        net_input = torch.cat([u, dt_feature], dim=1)
        return u + dt_t * self.g(net_input)

def write_prior_input_bin(path: Path, X: np.ndarray, dt: float):
    """
    Write binary input for the compiled prior.
    X: (N,2) float64
    """
    X = np.asarray(X, dtype=np.float64)
    if X.ndim != 2 or X.shape[1] != 2:
        raise ValueError(f"X must be (N,2), got {X.shape}")
    N = np.int64(X.shape[0])
    dt64 = np.float64(dt)
    with open(path, "wb") as f:
        f.write(N.tobytes())
        f.write(dt64.tobytes())
        f.write(X.tobytes(order="C"))


def read_prior_output_bin(path: Path) -> np.ndarray:
    """
    Read binary output from compiled prior.
    Returns Y_prior: (N,2) float64
    """
    with open(path, "rb") as f:
        raw = f.read()
    if len(raw) < 8:
        raise ValueError("Output file too small.")
    N = np.frombuffer(raw[:8], dtype=np.int64)[0]
    expect = 8 + int(N) * 2 * 8
    if len(raw) != expect:
        raise ValueError(f"Output size mismatch: got {len(raw)} bytes, expected {expect}.")
    arr = np.frombuffer(raw[8:], dtype=np.float64).reshape(int(N), 2)
    return arr.copy()


def call_compiled_prior(prior_exec: str, X: np.ndarray, dt: float, workdir: Path) -> np.ndarray:
    """
    Invoke compiled prior executable to compute one-step map on X.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    in_bin = workdir / "prior_in.bin"
    out_bin = workdir / "prior_out.bin"
    write_prior_input_bin(in_bin, X, dt)

    cmd = [prior_exec, str(in_bin), str(out_bin)]
    res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    if res.returncode != 0:
        raise RuntimeError(
            "Compiled prior failed.\n"
            f"Command: {' '.join(cmd)}\n"
            f"stdout:\n{res.stdout.decode('utf-8', errors='ignore')}\n"
            f"stderr:\n{res.stderr.decode('utf-8', errors='ignore')}\n"
        )
    return read_prior_output_bin(out_bin)


@torch.no_grad()
def rel_l2(pred: torch.Tensor, target: torch.Tensor, eps: float = 1e-12) -> float:
    num = torch.norm(pred - target, dim=-1)
    den = torch.norm(target, dim=-1).clamp_min(eps)
    return (num / den).mean().item()


def train_phi(
    Y_prior: torch.Tensor,
    Y_ref: torch.Tensor,
    cfg: TrainCfg,
    device: torch.device,
) -> nn.Module:
    ds = TensorDataset(Y_prior, Y_ref)
    loader = DataLoader(ds, batch_size=cfg.batch_size, shuffle=True, drop_last=False)

    # model = MLP(2, 2, width=cfg.width, depth=cfg.depth).to(device=device, dtype=cfg.dtype)
    model = ResidualCorrector(width=cfg.width, depth=cfg.depth).to(device=device, dtype=cfg.dtype)
    opt = torch.optim.AdamW(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)
    best_mse = float("inf")

    for ep in range(1, cfg.epochs + 1):
        model.train()
        loss_sum = 0.0
        n = 0
        for yp, yr in loader:
            yp = yp.to(device)
            yr = yr.to(device)
            opt.zero_grad(set_to_none=True)
            pred = model(yp, cfg.dt)
            loss = F.mse_loss(pred, yr)
            loss.backward()
            opt.step()
            loss_sum += loss.item() * yp.shape[0]
            n += yp.shape[0]

        # if ep == 1 or ep % 20 == 0:
        model.eval()
        with torch.no_grad():
            pred = model(Y_prior.to(device), cfg.dt)
            mse = F.mse_loss(pred, Y_ref.to(device)).item()
            r = rel_l2(pred, Y_ref.to(device))
        print(f"[Lie] epoch {ep:4d} | train_mse={loss_sum/max(1,n):.3e} | full_mse={mse:.3e} | relL2={r:.3e}")
        if mse < best_mse:
            best_mse = mse
            torch.save(model.state_dict(), "best_lie_corrector.pth")

    return model


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--dataset", type=str, required=True, help="Path to .npz produced by data.py")
    p.add_argument("--prior_exec", type=str, required=True, help="Path to compiled prior_oscillator_eigen executable")
    p.add_argument("--out_ts", type=str, default="lie_corrector_phi.ts", help="Output TorchScript path")
    p.add_argument("--workdir", type=str, default="./tmp_prior_io", help="Directory for binary IO to prior")
    p.add_argument("--device", type=str, default="cuda" if torch.cuda.is_available() else "cpu")
    p.add_argument("--epochs", type=int, default=5000)
    p.add_argument("--batch_size", type=int, default=1024)
    p.add_argument("--lr", type=float, default=2e-3)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--width", type=int, default=128)
    p.add_argument("--depth", type=int, default=3)
    args = p.parse_args()

    cfg = TrainCfg(
        batch_size=args.batch_size,
        epochs=args.epochs,
        lr=args.lr,
        seed=args.seed,
        width=args.width,
        depth=args.depth,
    )

    set_seed(cfg.seed)
    torch.set_default_dtype(cfg.dtype)

    device = torch.device(args.device)
    workdir = Path(args.workdir)

    # Load dataset
    npz = np.load(args.dataset)
    X = npz["X"].astype(np.float64)
    Y = npz["Y"].astype(np.float64)
    dt = float(npz["dt"])

    # Compute prior one-step outputs via compiled code
    print(f"[Lie] Calling compiled prior on N={X.shape[0]} with dt={dt} ...")
    Y_prior_np = call_compiled_prior(args.prior_exec, X, dt, workdir)

    # Convert to torch
    Y_prior = torch.from_numpy(Y_prior_np)
    Y_ref = torch.from_numpy(Y)

    # Train
    model = train_phi(Y_prior, Y_ref, cfg, device)

    model.load_state_dict(torch.load("best_lie_corrector.pth"))

    # Export TorchScript for C++ inference
    model_cpu = model.cpu().eval()
    scripted = torch.jit.script(model_cpu)
    out_ts = Path(args.out_ts)
    out_ts.parent.mkdir(parents=True, exist_ok=True)
    scripted.save(str(out_ts))
    print(f"[Lie] Saved TorchScript: {out_ts}")

    # Quick sanity check on a small batch
    with torch.no_grad():
        yp = Y_prior[:4096]
        yr = Y_ref[:4096]
        pred = model_cpu(yp, cfg.dt)
        print(f"[Lie] sanity relL2 (subset): {rel_l2(pred, yr):.3e}")


if __name__ == "__main__":
    main()
